# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(960, 540)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 90, 751, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.src_file_name_show = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.src_file_name_show.setEnabled(True)
        self.src_file_name_show.setReadOnly(True)
        self.src_file_name_show.setObjectName("src_file_name_show")
        self.horizontalLayout_3.addWidget(self.src_file_name_show)
        self.src_selector = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.src_selector.setObjectName("src_selector")
        self.horizontalLayout_3.addWidget(self.src_selector)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.stackedWidget = QtWidgets.QStackedWidget(self.verticalLayoutWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 100, 751, 23))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.dst_file_name_show = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.dst_file_name_show.setObjectName("dst_file_name_show")
        self.horizontalLayout.addWidget(self.dst_file_name_show)
        self.dst_selector = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.dst_selector.setObjectName("dst_selector")
        self.horizontalLayout.addWidget(self.dst_selector)
        self.operate_button = QtWidgets.QPushButton(self.page)
        self.operate_button.setGeometry(QtCore.QRect(670, 200, 80, 23))
        self.operate_button.setObjectName("operate_button")
        self.progress_show = QtWidgets.QProgressBar(self.page)
        self.progress_show.setGeometry(QtCore.QRect(0, 200, 651, 23))
        self.progress_show.setProperty("value", 0)
        self.progress_show.setInvertedAppearance(False)
        self.progress_show.setObjectName("progress_show")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(80, 30, 182, 21))
        self.label_3.setObjectName("label_3")
        self.block_size_selector = QtWidgets.QComboBox(self.page)
        self.block_size_selector.setGeometry(QtCore.QRect(210, 30, 81, 21))
        self.block_size_selector.setEditable(False)
        self.block_size_selector.setObjectName("block_size_selector")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(380, 30, 111, 21))
        self.label_4.setObjectName("label_4")
        self.color_selector = QtWidgets.QComboBox(self.page)
        self.color_selector.setGeometry(QtCore.QRect(530, 30, 81, 21))
        self.color_selector.setObjectName("color_selector")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AsciiConverter"))
        self.label.setText(_translate("MainWindow", " 源文件 "))
        self.src_selector.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "目标文件"))
        self.dst_selector.setText(_translate("MainWindow", "..."))
        self.operate_button.setText(_translate("MainWindow", "开始"))
        self.label_3.setText(_translate("MainWindow", "单个字符大小"))
        self.label_4.setText(_translate("MainWindow", "是否输出为彩色"))

