# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1127, 883)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(270, 200, 591, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.src_picture_path_show = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.src_picture_path_show.setObjectName("src_picture_path_show")
        self.horizontalLayout_3.addWidget(self.src_picture_path_show)
        self.src_picture_selector = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.src_picture_selector.setObjectName("src_picture_selector")
        self.horizontalLayout_3.addWidget(self.src_picture_selector)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.stackedWidget = QtWidgets.QStackedWidget(self.verticalLayoutWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 20, 591, 23))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.block_size_selector = QtWidgets.QComboBox(self.horizontalLayoutWidget_4)
        self.block_size_selector.setObjectName("block_size_selector")
        self.horizontalLayout_4.addWidget(self.block_size_selector)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 120, 589, 21))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.txt_selected = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5)
        self.txt_selected.setObjectName("txt_selected")
        self.horizontalLayout_5.addWidget(self.txt_selected)
        self.picture_selected = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5)
        self.picture_selected.setObjectName("picture_selected")
        self.horizontalLayout_5.addWidget(self.picture_selected)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 220, 589, 23))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dst_picture_path_show = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.dst_picture_path_show.setObjectName("dst_picture_path_show")
        self.horizontalLayout.addWidget(self.dst_picture_path_show)
        self.dst_picture_selector = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.dst_picture_selector.setObjectName("dst_picture_selector")
        self.horizontalLayout.addWidget(self.dst_picture_selector)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 290, 589, 23))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dst_txt_path_show = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.dst_txt_path_show.setObjectName("dst_txt_path_show")
        self.horizontalLayout_2.addWidget(self.dst_txt_path_show)
        self.dst_txt_selector = QtWidgets.QToolButton(self.horizontalLayoutWidget_2)
        self.dst_txt_selector.setObjectName("dst_txt_selector")
        self.horizontalLayout_2.addWidget(self.dst_txt_selector)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.start_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.start_button.setObjectName("start_button")
        self.horizontalLayout_6.addWidget(self.start_button)
        self.end_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.end_button.setObjectName("end_button")
        self.horizontalLayout_6.addWidget(self.end_button)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1127, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.src_picture_selector.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "请设置单个ascii码的大小"))
        self.label_4.setText(_translate("MainWindow", "请选择导出格式"))
        self.txt_selected.setText(_translate("MainWindow", "文本"))
        self.picture_selected.setText(_translate("MainWindow", "图片"))
        self.dst_picture_selector.setText(_translate("MainWindow", "..."))
        self.dst_txt_selector.setText(_translate("MainWindow", "..."))
        self.start_button.setText(_translate("MainWindow", "确定"))
        self.end_button.setText(_translate("MainWindow", "关闭"))

